### ISSUE TITLE
This project's git folder breaks the "ls" command.

### ISSUE THREAD

**Issue by zippynk** [gmittal/stream#1]
I tried cd'ing into the project's directory, and typing "ls". However, no files appeared, meaning that LS is claiming that there are no files in the folder. Since I know that there are files in the folder, I'm assuming this must be some weird problem with filesystems and stuff, unless, for some reason, there are no files in the project's git repository.

**Comment by gmittal** [comment]
??!

There should be files in the git repo.

**Comment by zippynk** [comment]
I think I posted this as a joke when there weren't files.
